# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: be130e37b358f057c60694d6161a75790e397f3718587283dc455f5192c96b2fd6ae2a240c0f9c3311bb83edc201e5bc949608d2a18628735382ef79014ea78b

test:
  secret_key_base: 168682cf9c2f7d360c2cfd162e36731722689d4660caaf8789668c45f190aaf2f2d6c5b5fafd77ee9f9d5844e2adc3588cff63074a5543301e8ac08a41060097

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
